In [1]:
import subprocess
import os

import pandas as pd
import numpy as np

from datetime import datetime

import requests
import json

In [2]:

def get_johns_hopkins():
    ''' Get data by a git pull request, the source code has to be pulled first
        Result is stored in the predifined csv structure
    '''
    git_pull = subprocess.Popen( "/usr/bin/git pull" ,
                         cwd = os.path.dirname( '/mnt/368AE7F88AE7B313/Files_Programming/Git/ads_covid-19-sem/data/raw/COVID-19/' ),
                         shell = True,
                         stdout = subprocess.PIPE,
                         stderr = subprocess.PIPE )
    (out, error) = git_pull.communicate()


    print("Error : " + str(error))
    print("out : " + str(out))

In [3]:
get_johns_hopkins()

Error : b'From https://github.com/CSSEGISandData/COVID-19\n   66e95c6e..93eadb0a  web-data   -> origin/web-data\n'
out : b'Already up to date.\n'

In [4]:
path = '/mnt/368AE7F88AE7B313/Files_Programming/Git/ads_covid-19-sem/data/raw/COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv'
df = pd.read_csv(path)

In [5]:
df.columns

Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '6/20/20', '6/21/20', '6/22/20', '6/23/20', '6/24/20', '6/25/20',
       '6/26/20', '6/27/20', '6/28/20', '6/29/20'],
      dtype='object', length=164)

In [7]:
def store_relational_JH_data():
    ''' Transformes the COVID data in a relational data set

    '''

    data_path='/mnt/368AE7F88AE7B313/Files_Programming/Git/ads_covid-19-sem/data/raw/COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv'
    pd_raw=pd.read_csv(data_path)

    pd_data_base=pd_raw.rename(columns={'Country/Region':'country',
                      'Province/State':'state'})

    pd_data_base['state']=pd_data_base['state'].fillna('no')

    pd_data_base=pd_data_base.drop(['Lat','Long'],axis=1)


    pd_relational_model=pd_data_base.set_index(['state','country'])                                 .T                                                              .stack(level=[0,1])                                             .reset_index()                                                  .rename(columns={'level_0':'date',
                                                   0:'confirmed'},
                                                  )

    pd_relational_model['date']=pd_relational_model.date.astype('datetime64[ns]')

    pd_relational_model.to_csv('/mnt/368AE7F88AE7B313/Files_Programming/Git/ads_covid-19-sem/data/processed/COVID_relational_confirmed.csv',sep=';',index=False)
    print(' Number of rows stored: '+str(pd_relational_model.shape[0]))

In [8]:
store_relational_JH_data()

 Number of rows stored: 42560

In [6]:
path2 = '/mnt/368AE7F88AE7B313/Files_Programming/Git/ads_covid-19-sem/data/processed/COVID_small_flat_table.csv'

In [7]:

df2 = pd.read_csv(path2,sep=';')

In [8]:
df2.tail(46)

           date   Italy       US   Spain  Germany  Korea, South
114  2020-05-15  223885  1449026  230183   175233         11037
115  2020-05-16  224760  1474127  230698   175752         11050
116  2020-05-17  225435  1493131  230698   176369         11065
117  2020-05-18  225886  1514839  231606   176551         11078
118  2020-05-19  226699  1535337  232037   177778         11110
119  2020-05-20  227364  1558949  232555   178473         11122
120  2020-05-21  228006  1584486  233037   179021         11142
121  2020-05-22  228658  1608623  234824   179710         11165
122  2020-05-23  229327  1630450  235290   179986         11190
123  2020-05-24  229858  1651239  235772   180328         11206
124  2020-05-25  230158  1670209  235400   180600         11225
125  2020-05-26  230555  1689057  236259   181200         11265
126  2020-05-27  231139  1707423  236259   181524         11344
127  2020-05-28  231732  1730259  237906   182196         11402
128  2020-05-29  232248  1754747  238564   182922         11441
129  2020-05-30  232664  1778993  239228   183189         11468
130  2020-05-31  232997  1799122  239479   183410         11503
131  2020-06-01  233197  1816476  239638   183594         11541
132  2020-06-02  233515  1837367  239932   183879         11590
133  2020-06-03  233836  1857248  240326   184121         11629
134  2020-06-04  234013  1878543  240660   184472         11668
135  2020-06-05  234531  1903854  240978   184924         11719
136  2020-06-06  234801  1926538  241310   185450         11776
137  2020-06-07  234998  1944309  241550   185750         11814
138  2020-06-08  235278  1961781  241717   186109         11852
139  2020-06-09  235561  1979868  241966   186506         11902
140  2020-06-10  235763  2000702  242280   186522         11947
141  2020-06-11  236142  2023590  242707   186691         12003
142  2020-06-12  236305  2048986  243209   187226         12051
143  2020-06-13  236651  2074526  243605   187267         12085
144  2020-06-14  236989  2094058  243928   187518         12121
145  2020-06-15  237290  2114026  244109   187682         12155
146  2020-06-16  237500  2137731  244328   188252         12198
147  2020-06-17  237828  2163290  244683   188604         12257
148  2020-06-18  238159  2191052  245268   189817         12306
149  2020-06-19  238011  2222579  245575   190299         12373
150  2020-06-20  238275  2255297  245938   190670         12421
151  2020-06-21  238499  2281655  246272   191272         12438
152  2020-06-22  238720  2312302  246504   191768         12484
153  2020-06-23  238833  2347491  246752   192480         12535
154  2020-06-24  239410  2382327  247086   192871         12563
155  2020-06-25  239706  2422299  247486   193371         12602
156  2020-06-26  239961  2467554  247905   194036         12653
157  2020-06-27  240136  2510151  248469   194458         12715
158  2020-06-28  240310  2548996  248770   194693         12757
159  2020-06-29  240436  2590552  248970   195042         12800